name: e_con
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  get_it: ^7.2.0
  provider: ^6.0.4
  rxdart: ^0.27.5
  shimmer: ^2.0.0
  url_launcher: ^6.1.6
  flutter_spinkit: ^5.1.0
  sliver_tools: ^0.2.8
  convex_bottom_bar: ^3.1.0+1
  qr_code_scanner: ^1.0.1
  awesome_dialog: ^3.0.2
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  scan: ^1.6.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  jwt_decode: ^0.3.1
  webview_flutter: ^4.0.0
  intl: ^0.18.0
  date_time_picker: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  # lint: ^1.0.0
  # dart_style: ^2.2.4
  # flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/illustrations/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins_reguler.ttf
        - asset: fonts/poppins_medium.ttf
          weight: 500
        - asset: fonts/poppins_bold.ttf
          weight: 700
