name: e_con
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  get_it: ^7.2.0
  provider: ^6.0.4
  rxdart: ^0.27.5
  shimmer: ^2.0.0
  url_launcher: ^6.1.6
  flutter_spinkit: ^5.1.0
  sliver_tools: ^0.2.8
  convex_bottom_bar: ^3.1.0+1
  qr_code_scanner: ^1.0.1
  awesome_dialog: ^3.0.2
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  scan: ^1.6.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  jwt_decode: ^0.3.1
  webview_flutter: ^4.0.2
  intl: ^0.17.0
  date_time_picker: ^2.1.0
  qr: ^3.0.1
  image_gallery_saver: ^1.7.1
  share_plus: ^6.3.0
  path_provider: ^2.0.11
  salomon_bottom_bar: ^3.3.1
  connectivity_plus: ^2.2.0
  top_snackbar_flutter: ^3.0.0+1
  flutter_bloc: ^8.1.1
  oauth2: ^2.0.1
  firebase_core: ^2.4.1
  onesignal_flutter: ^3.5.0
  timelines: ^0.1.0
  webview_flutter_wkwebview: ^3.1.1

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_test:
    sdk: flutter
  # lint: ^1.0.0
  # dart_style: ^2.2.4
  # flutter_lints: ^2.0.1

flutter:
  ios: 
    bundle_identifier: com.npedigital.econ
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/illustrations/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins_reguler.ttf
        - asset: fonts/poppins_medium.ttf
          weight: 500
        - asset: fonts/poppins_bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"
