name: e_con
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  get_it: ^7.2.0
  provider: ^6.0.4
  rxdart: ^0.27.5
  shimmer: ^2.0.0
  url_launcher: ^6.1.6
  flutter_spinkit: ^5.1.0
  sliver_tools: ^0.2.8
  convex_bottom_bar: ^3.1.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  # dart_style: ^2.2.4
  # flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins_reguler.ttf
        - asset: fonts/poppins_medium.ttf
          weight: 500
        - asset: fonts/poppins_bold.ttf
          weight: 700